# std_msgs/Header
std_msgs/Header header

uint8   ID
uint8   ClassCategory
uint8   MovingFlag
uint16  MotionCategory
uint8   TrackingState

float32 QualityLevel
float32 LengthQualityLevel
float32 WidthQualityLevel
float32 HeadingAngleQualityLevel

float32 Length
float32 Width

float32 RelPosX
float32 RelPosY
float32 RelVelX
float32 RelVelY
float32 RelAccelX
float32 RelAccelY
float32 AbsoluteVel
float32 HeadingAngle
